dataset: mot_crowdhuman

mot_path_train: data/MOT20
mot_path_val: data/MOT20

crowdhuman_train_split: train_val
train_split: mot20_train_cross_val_frame_0_0_to_0_5_coco
val_split: mot20_train_cross_val_frame_0_5_to_1_0_coco

lr: 0.0002
lr_backbone: 0.00002

epochs: 40
lr_drop: 10